spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/todo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibername:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug